name = "Rabauken Craft 3"
author = "Anton"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d5f995310f3032a45f9cb2bf519389b40dced0e96c8c91329e7dcc35ebd1766"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
