name = "Rabauken Craft 3"
author = "Anton"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa8b7c87185476598a1218f349abdfade13d3ce46d62bb4b2be364134c41335b"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
