name = "Rabauken Craft 3"
author = "Anton"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1c4af5d0c476a62d161b5b1cb998ef38a3978175806ddef4b5524f55594f855"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
